@HOST = http://localhost:8080/api

POST {{HOST}}/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1ZjkwNzlhMC1iYmJkLTQ1ZWEtODJjZS0wZjliYzlhOGYyMmUiLCJ1aWRQcm9maWxlIjoiNWVkN2U0MzctODQ2NS00M2UyLTg2ZDktMzBlNmExMmIyN2NmIiwiaWF0IjoxNjUxODEzNzU5LCJleHAiOjE2NTE5MDAxNTl9.PITEjwxcahB9QGZK935GmV9bqU6xAHEaUPKfBcjL8Q4

{
  "name":"Produto 1",
  "type": "Um tipo qualquer",
  "description": "Qualquer descrição",
  "price": 1500.99
}
