@HOST = http://localhost:8080/api

get {{HOST}}/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVWlkIjoiNmE0ZTFiYjItNTkyYS00Yjk4LTg5ODYtODg1NmMyZGU4NzkwIiwicHJvZmlsZVVpZCI6ImIzOTk3Yjc2LTM2NjMtNDg2NS05NTg2LTc4ZTU4MzgwZjE0MCIsImlhdCI6MTY2NTgwNzg2OSwiZXhwIjoxNjY1ODk0MjY5fQ.JFvcmC0UCpCELB4b6p1RiLOzRCj5jJpKBdNySmtog68
