@HOST = http://localhost:8080/api

get {{HOST}}/products/353f2ff7-01c3-4aa9-8ab8-dce752b58f1e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVWlkIjoiMDc1YTg4NmUtNTcwMy00NzZjLWI0NmItZTkwMTQ2ZTU1YjQ3IiwicHJvZmlsZVVpZCI6Ijk1NjczZmFjLWYwOTgtNDRhNC1hZTYxLTkxNmYwMTBlYjk4ZiIsImlhdCI6MTY2NTk0NzY0MiwiZXhwIjoxNjY2MDM0MDQyfQ.qDaQSo8saCg8hO9RyYMW-fNlCH7qxtArRdrBmfsLTZs
