version: "3"

services:

  app:
    build:
      context: .
    container_name: growbase
    # command: npm run dev
    ports:
      - 8080:8080
      - 9229:9229
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    networks:
      - growbase
    tty: true

  db:
    image: postgres
    restart: always
    container_name: postgres-growbase
    environment:
      POSTGRES_PASSWORD: growdev2022
      POSTGRES_USER: growdev
      POSTGRES_DB: growbase
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - growbase

  redis:
    image: redis
    container_name: redis-growbase
    command: redis-server --requirepass growdev2022
    ports:
      - 6379:6379
    networks:
      - growbase

networks:
  growbase:
    driver: bridge

volumes:
  postgres:
