@HOST = http://localhost:8080/api

GET {{HOST}}/auth HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVWlkIjoiOTc1ZTY3ZjMtYmMwMS00MTJkLWE2YTAtNTBiNzU4ZDFiMTQ2IiwicHJvZmlsZVVpZCI6IjZkMGI2ZDA2LTFjNTctNGNjNC04ZGI5LTI0ZThkYThmOTEyMSIsImlhdCI6MTY3ODEyNTk5NSwiZXhwIjoxNjc4MjEyMzk1fQ.Y1KKxHB5JYAq-VDh901GD1uG0bCwxmLQuZIc4bq1Ifc
