@HOST = http://localhost:8080/api

POST {{HOST}}/signup HTTP/1.1
Content-Type: application/json

{
  "name": "Guilherme Niches",
  "email": "gniches.quench@gmail.com",
  "password": "123456",
  "document": "07608155000"
}
