@HOST = http://localhost:8080/api

PUT {{HOST}}/categories/a3a75c37-84be-435b-a360-d6fccf3c0a96 HTTP/1.1
Content-Type: application/json

{
  "name":"FRUTAS",
  "description": "FRUTAS",
  "image": {
    "uid": "",
    "url": "any"
  }
}
