@HOST = http://localhost:8080/api

PUT {{HOST}}/account/recovery-password HTTP/1.1
Content-Type: application/json

{
  "link": "$2b$08$rx7LDpjR9N8U9S2mE08g.ulI2FfXt3a1pUq5167QUWEj7WwIPAQxi",
  "password": "growdev"
}
