@HOST = http://localhost:8080/api

PUT {{HOST}}/account/update-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVWlkIjoiYmZhNDQ4NzYtNTdiOS00OGEwLTkwNGMtNzJkZWQzNThmMGNjIiwicHJvZmlsZVVpZCI6ImNjNzliYWEwLWIwZTItNDY4Ni1iM2VkLTVhY2E5NTRlMzY0NyIsImlhdCI6MTY3NjM4MTQ3NywiZXhwIjoxNjc2NDY3ODc3fQ.oF7ONeglX0YIdI-CA9AD8YMABU_5CfkUnmKpW_WTD6Q

{
  "password": "123456"
}
